### ISSUE TITLE
Reproducing first training step

### ISSUE THREAD

**Issue by andreemic** [salesforce/HIVE#2]
Hey, great job on this project! Really exciting work.

I want to reproduce the first part of your training process (fine-tuning IP2P) on SD2.1 768x768 but having some trouble.

I've tried to piece together the original IP2P training config and your generate config for SD2.1 but the layer params don't match up between my config and my checkpoint. **Do you have any idea how to make the checkpoint and model match?**

## My model
https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-ema-pruned.ckpt

## My config
```yaml
# train.yaml
model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm_edit_v21.LatentDiffusion
  params:
    ckpt_path: checkpoints/v2-1_768-ema-pruned.ckpt
    # ...
```

## The errors

I get a lot of errors like these when starting training:
```
size mismatch for model.diffusion_model.input_blocks.2.1.x.y.z: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current 
model is torch.Size([320, 768]).
```
The mismatches are between a shape element being 1024 in checkpoint vs. 768 in the model definition, or something like `torch.Size([640, 640])` vs. `torch.Size([640, 640, 1, 1])`

## Exact errors
<img width="978" alt="Screenshot 2023-05-07 at 12 03 12" src="https://user-images.githubusercontent.com/27695722/236670948-b901f110-4411-4c31-ae0f-979a892ba029.png">
